### ISSUE TITLE
CircuitBreaker should publish events as an event stream and clients should be able to subscribe

### ISSUE THREAD

**Issue by RobWin** [RobWin/javaslang-circuitbreaker#13]
A CircuitBreaker should store (a configurage number of) handled exceptions so that you can retrieve the list of exceptions which have triggered the CB. 
This helps in cases where you have to analyze some error.

**Comment by RobWin** [comment]
I think I refactor this again. The CircuitBreaker should not store exceptions itself, but publish events (event stream) which contain the exception. 
A system which is interested in these exceptions (events) can subscribe to the event and store the exception in a CircularBuffer itself. The CircuitBreaker is lightweight again and extendable. I think I introduce RxJava to make the CircuitBreaker an Observable. That way I don't have to implement an EventBus and use a new specification which is included in Java9.

**Comment by storozhukBM** [comment]
Hi @RobWin 
Please consider usage of [ReactiveStreams](https://github.com/reactive-streams/reactive-streams-jvm/tree/v1.0.0) specification. With this interfaces the implementation will be meter of choice for library users [RxJava, Akka, Reactor...]. It also will be compatible with Java9's [Flow](http://gee.cs.oswego.edu/dl/jsr166/dist/docs/java/util/concurrent/Flow.html)

**Comment by RobWin** [comment]
Yes, I will just add `org.reactivestreams:reactive-streams:1.0.0` as a compile dependency
