### ISSUE TITLE
Write benchmark for CircularFifoBuffer and possibly optimise it

### ISSUE THREAD

**Issue by storozhukBM** [RobWin/javaslang-circuitbreaker#15]
Hi, @RobWin 

I've highly optimised and fully tested analog of your `CircularFifoBuffer` in my other project.
So if don't mind I'd be happy to contribute it to this project via pull request after rate limiter implementation.
Just assign this issue on me.

**Comment by RobWin** [comment]
Hi,

every contribution is great. Feel free to optimize the implementation.

**Comment by storozhukBM** [comment]
Seems that i've screwed up with naming and all related commits weren't linked to this issue. Done in scope of https://github.com/RobWin/javaslang-circuitbreaker/pull/29.
