### ISSUE TITLE
Modularize project into separate Gradle modules

### ISSUE THREAD

**Issue by emmanueltouzery** [RobWin/javaslang-circuitbreaker#22]
at this point I use only the retry feature of circuitbreaker, but with 0.7 circuitbreaker now also pulls in for instance rxjava and other things which I don't need for such a small functionality as the retry feature.

Do you think maybe it would make sense to split the retry feature in its own artifact that the main circuitbreaker library would depend upon, so that it would be possible to depend only on that bit?

**Comment by RobWin** [comment]
Hi,
yes that makes sense. I will modularize the project into separate Gradle modules soon.

**Comment by emmanueltouzery** [comment]
right and so there'll be several separate maven artifacts to depend on?

**Comment by RobWin** [comment]
yes

**Comment by RobWin** [comment]
Sry, but I have to tell you that the next version of Retry has been refactored and requires RxJava as well. If you just need the old version of Retry, I would suggest you to copy the old classes.

**Comment by emmanueltouzery** [comment]
Thank you for the heads up!  By curiosity, may i ask what rxjava brings to the table for retry? Does ot only help the implementation, or does it add user-visible features?

If it doesn't bring user-visible features that are handy, i'll probably look for (or worst-case create) a tiny no-dependency library for retrying. I already stumbled on retry4j.

**Comment by RobWin** [comment]
Retry (like CircuitBreaker or RateLimiter) emits an events when it has to retry a function. It's a success event when a retry was successful and a error event when even all retries have failed. The event contains a timestamp, number of retry attempts, the last exception and a logical name of your decorated function. You can either log the events, or push retry statistics to an InfluxDb or do whatever you have to do to get more insight in your system.

Do you know the library async-retry on github?

**Comment by RobWin** [comment]
https://github.com/nurkiewicz/async-retry/blob/master/README.md

**Comment by emmanueltouzery** [comment]
thanks for the answer & the tips! this retry event is really something useful. I'll think it over. closing this now i then guess.

**Comment by RobWin** [comment]
Thx.
