### ISSUE TITLE
Log and listener for transitions

### ISSUE THREAD

**Issue by flozano** [RobWin/javaslang-circuitbreaker#3]
It would be great if CircuitBreaker could log the transitions that it makes. Having a listener for the transition changes would help a lot also, in order to hook specific actions for specific state changes.

**Comment by flozano** [comment]
Maybe it's better if I explain with detail my use-case:

I have written a wrapper for my cache abstraction layer that uses circuit-breaker to deal with network issues between my memcached servers and my java components.

In order to keep consistency of the cache, when the CB transitions from HALF_CLOSED to CLOSED I need to flush the underlying cache, because the cache will be in stale state. Now I'm doing it in the code consuming CB, by wrapping the calling code, but it would be great to have a centralized way of doing it, with something like:
```java
@FunctionalInterface
interface CircuitBreakerStateChangeListener {
    void onStateChange(State previous, State new, Throwable cause);
}
```
and the ability to add this in the circuit-breaker builder.

**Comment by RobWin** [comment]
Hi,
good idea. Do you think you can create a PR?
I'm busy with Javaslang and Swagger2markup atm.

**Comment by RobWin** [comment]
I have a better idea. A callback register method would be sufficient where clients can register a Consumer function which is triggered when the state changes.

**Comment by RobWin** [comment]
But basically it's the same implementation

**Comment by RobWin** [comment]
I started to implement it

**Comment by RobWin** [comment]
See https://github.com/RobWin/javaslang-circuitbreaker#add-a-custom-event-listener

**Comment by RobWin** [comment]
I've released v0.1.7 which implements this issue.

**Comment by flozano** [comment]
I am sorry, I don't have properly configured the github notices filtering in my email, and I missed your comments. Thanks a lot for taking care of the issue, and congrats for this great tool.

**Comment by RobWin** [comment]
Np. Thx for the kind words :)
