### ISSUE TITLE
Ability to 'force' opening of a circuit breaker

### ISSUE THREAD

**Issue by flozano** [RobWin/javaslang-circuitbreaker#33]
It would be great if a developer can force the transition to OPEN to happen whenever desired.

The use-case I have is a failing backend service that is connected from several nodes. If a node detects a failure in this backend service, in order to minimize potential inconsistency with other nodes it's best if this node can advice all other nodes to move to OPEN on their own circuit-breaker instance, as soon as possible.

I understand the communication between nodes and such is fully beyond the scope of this project, but at minimum it would be needed:
 - to be able to force a transition to a given circuit-breaker
 - to be able to detect in the `CircuitBreakerEventListener` that the transition was 'forced'.

What do you think?

**Comment by RobWin** [comment]
Good idea. We can add that, but please check the new API. The CircuitBreakerEventListener does not exist anymore. The CircuitBreaker emits an event stream now which you can subscribe to and handle it this StateTransitionEvents.

**Comment by flozano** [comment]
ah, seems simple enough, I will check :) in any case I guess the request still applies...

**Comment by RobWin** [comment]
Would you like to contribute this feature?

**Comment by RobWin** [comment]
I've implemented it now.
In the upcoming version you can force state transitions like this:

`circuitBreaker.transitionToOpenState();`
