### ISSUE TITLE
Integration with Spring Reactor

### ISSUE THREAD

**Issue by apischan** [RobWin/javaslang-circuitbreaker#35]
Is there any way to use this library with Spring Reactor? If no is there any plans to integrate it?

**Comment by RobWin** [comment]
Hi,

What exactly so you want to do?
You can either convert RxJava to Spring Reactor streams by using reactor-adapter.
If you need a Spring Reactor Operator, I plan to create one. See https://github.com/reactor/reactor-addons/issues/48

**Comment by RobWin** [comment]
Btw if you like this librar, we would love to get your GitHub Star.

**Comment by apischan** [comment]
Yes thank you! Have sense))
p.s. Starred :+1:

**Comment by michael-barker** [comment]
Will this be in 0.12.0?
