### ISSUE TITLE
How to set timeout to limit operation execution time?

### ISSUE THREAD

**Issue by noorulhaq** [RobWin/javaslang-circuitbreaker#36]
Hi,
I am unable to find a way to set timeout in circuitbreaker configuration to time bound operation execution like we have in Hystrix.

**Comment by RobWin** [comment]
Hi,
thx for evaluating this library. If you like this library, we would love to get your GitHub Star.

I assume you mean the configuration option `execution.isolation.thread.timeoutInMilliseconds` of Hystrix? 
Bulk Heading (execution isolation) is not in the scope of this library. The library let you choose if you want to execute your business logic sync or async. You can choose if you want to use a pure `ExecutorService`, a `CompletableFuture` or RxJava and configure the timeout. See: http://www.esynergy-solutions.co.uk/blog/asynchronous-timeouts-completablefutures-java-8-and-java-9-raoul-gabriel-urma

But I suggest, if you send a message to a remote system, you should set a timeout on the protocol level (e.g. HTTP).  

If you use RxJava (which I suggest), you could use the `timeout` operator.

**Comment by noorulhaq** [comment]
Yes, you are right about setting timeout at protocol level, but unfortunately this is not always possible, especially when you are using third partly libraries. Also, the usecase may not always be a network call.
Having said that if we have timeout option in circuit breaker than it can short circuit the call to time taking operation, which is not possible if I use timeout of RxJava.

**Comment by RobWin** [comment]
Why does RxJava `timeout` not work for you?
Do you want to execute your bussiness logic sync or async?

**Comment by noorulhaq** [comment]
Timeout will not work in same manner as circuit breaker. The operation for which you set timeout in RxJava  will always take exection time equal to timeout. It does fail fast like curcuit breaker.

**Comment by RobWin** [comment]
You could write your own Higher order function which wraps your Supplier function 

```
    static <T> Try.CheckedSupplier<T>  timeoutCallable(CircuitBreaker circuitBreaker, ExecutorService executor, Callable<T> callable, Duration timeout){
        return () -> {
            Future<T> future = executor.submit(callable);
            return CircuitBreaker.decorateSupplier(circuitBreaker, () -> future.get(timeout.toMillis(), TimeUnit.MILLISECONDS));
        };
    }
```

Atm is not compilable, I will check the snippet tomorrow.

**Comment by RobWin** [comment]
You can combine RxJava's timeout operator with the Javaslang-CircuitBreaker's RxJava operator. See Readme.

**Comment by noorulhaq** [comment]
Last option seems apealing. I will get back on it once confirmed.

**Comment by RobWin** [comment]
Please tell me, if it works for you.
