### ISSUE TITLE
Decorate a method which returns a CompletableFuture

### ISSUE THREAD

**Issue by mniebla** [RobWin/javaslang-circuitbreaker#43]
In the docs the section on working with `CompletableFuture` looks like

```
Supplier<String> decoratedSupplier = CircuitBreaker
        .decorateSupplier(circuitBreaker, () -> "This can be any method which returns: 'Hello");

CompletableFuture<String> future = CompletableFuture.supplyAsync(decoratedSupplier)
        .thenApply(value -> value + " world'");
```

Doesn't seem like there is a straightforward to work with existing asynchronous code that may already return `CompletableFuture`, for example lets say I wanted to use a circuit-breaker on something that implements:

```
public interface Client {
    public CompletableFuture<String> get();
}
```

Would the recommended way to do this be:
  1. wrapping the client call in a `Supplier`
  2. implement a `decorateSupplierOfCompletableFuture` method that  does `Supplier.get()` after the call to `CircuitBreakerUtils.isCallPermitted(circuitBreaker)`

???

Thanks.

**Comment by RobWin** [comment]
Hi, thx for evaluating this library. If you like this library, we would love to get your GitHub Star.

I guess `Client.get()`  is not lazy, but runs the the businees logic as soon as you invoke `Client.get()`?
I will add a new method `decorateCompletableFuture` to the `CircuitBreaker`.

```
    static <T> Supplier<CompletableFuture<T>> decorateCompletableFuture(CircuitBreaker circuitBreaker, Supplier<CompletableFuture<T>> supplier){
        return () -> {
            CircuitBreakerUtils.isCallPermitted(circuitBreaker);
            StopWatch stopWatch = StopWatch.start(circuitBreaker.getName());
            return supplier.get().whenComplete((returnValue, throwable) -> {
                if (returnValue != null) {
                    circuitBreaker.onSuccess(stopWatch.stop().getProcessingDuration());
                } else {
                    circuitBreaker.onError(stopWatch.stop().getProcessingDuration(), throwable);
                }
            });
        };
    }
```

You can use it as follows: 

```
Supplier<CompletableFuture<String>> supplier = CircuitBreaker.decorateCompletableFuture(circuitBreaker, Client::get);

CompletableFuture<String> decoratedCompletableFuture = supplier.get();
```

Kind regards,
Robert

**Comment by RobWin** [comment]
I hope this works for you.

**Comment by goldobin** [comment]
Hi! Have recently made the same thing in my fork of this library. You can find commit [here](https://github.com/goldobin/javaslang-circuitbreaker/commit/a2925788d77c37ca7a8d56a9634e593e4be71f91). This commit also contains implementation of AsyncRetry addressing retries with completion stage. Probably it would help as well.

**Comment by RobWin** [comment]
Hi,

very nice. Your solution is better than mine. 
We would be happy, if you would like to contribute it.
Just create a PR, but please change the version 
👍
