### ISSUE TITLE
Write benchmark for RingBitSet and optimize peformance

### ISSUE THREAD

**Issue by RobWin** [RobWin/javaslang-circuitbreaker#7]

**Comment by jhalterman** [comment]
Hi @RobWin - For a reference on this issue, I recently added a circuit breaker impl to [Failsafe](https://github.com/jhalterman/failsafe) that uses a similar bitset approach to tracking failures. Positive and negative (success/failure) cardinality is updated as the bitset is changed, so it doesn't never needs to be recomputed and should perform pretty good. Have a look:

https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/internal/util/CircularBitSet.java
https://github.com/jhalterman/failsafe/blob/master/src/test/java/net/jodah/failsafe/internal/util/CircularBitSetTest.java

Cheers

**Comment by RobWin** [comment]
Thx. I have a look at it.
